apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-pv
  labels:
    app: syncthing
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: syncthing-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/syncthing
