apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-pv
  labels:
    app: uptime-kuma
spec:
  capacity:
    storage: 4Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: uptime-kuma-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/uptime-kuma
