apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-proxmox
  namespace: homepage
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: homepage-proxmox
    template:
      engineVersion: v2
      data:
        proxmox.yaml: |
          lab:
            url: https://192.168.1.10:8006
            token: {{ .proxmox_token }}
            secret: {{ .proxmox_secret }}
  data:
    - secretKey: proxmox_token
      remoteRef:
        key: homepage_proxmox_token
    - secretKey: proxmox_secret
      remoteRef:
        key: homepage_proxmox_secret
