apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocket-id-postgres-pv
  labels:
    app: pocket-id
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  mountOptions:
    - hard
    - nfsvers=3
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pocket-id-postgres-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/pocket-id/postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocket-id-data-pv
  labels:
    app: pocket-id
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pocket-id-data-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/pocket-id/data
