apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: pocket-id
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        username: pocketid
        password: "{{ .password }}"
        connection_string: "postgres://pocketid:{{ .password }}@pocket-id-postgres-rw.pocket-id.svc.cluster.local:5432/pocketid?sslmode=disable"
  data:
    - secretKey: password
      remoteRef:
        key: pocket_id_db_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: encryption_key
      remoteRef:
        key: pocket_id_encryption_key
