# Just hardcode secrets. 'cause yolo
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: immich
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: immich