apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 1
  storage:
    storageClass: nfs-csi-postgres
    size: 10Gi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.12
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      database: default
      owner: admin
      secret:
        name: db-secret
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;