apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 1
  storage:
    storageClass: nfs-csi-postgres
    size: 10Gi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.12
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  managed:
    roles:
      - name: ${postgres_user}
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: db-secret
  bootstrap:
    initdb:
      database: default
      owner: ${postgres_user}
      secret:
        name: db-secret
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;