# Just hardcode secrets. 'cause yolo
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: postgres
type: Opaque
stringData:
  username: ${postgres_user}
  password: ${postgres_password}