apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescaledb
  namespace: metrics-exporter
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: timescaledb
    major: 18
  imagePullPolicy: IfNotPresent
  postgresUID: 1000
  postgresGID: 1000
  storage:
    size: 100Gi
    pvcTemplate:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 100Gi
      storageClassName: nfs-csi
      volumeName: timescaledb-pv
  postgresql:
    shared_preload_libraries:
      - "timescaledb"
  managed:
    roles:
      - name: admin
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: timescaledb-secret
  bootstrap:
    initdb:
      database: admin
      owner: admin
      secret:
        name: timescaledb-secret
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
