apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: timescaledb-metrics-exporter-db
  namespace: metrics-exporter
spec:
  name: metrics_exporter
  owner: admin
  cluster:
    name: timescaledb
