apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metrics-exporter-steam
  namespace: metrics-exporter
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: metrics-exporter-steam
  data:
    - secretKey: steam_api_key
      remoteRef:
        key: metrics_exporter_steam_api_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: timescaledb-secret
  namespace: metrics-exporter
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: timescaledb-secret
    template:
      data:
        username: admin
        password: "{{ .password }}"
        database_url: "postgres://admin:{{ .password | urlquery }}@timescaledb-rw:5432"
  data:
    - secretKey: password
      remoteRef:
        key: metrics_exporter_db_password
