apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-pvc
  namespace: kube-system
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
