apiVersion: v1
kind: Secret
metadata:
    name: sops
    namespace: flux-system
type: Opaque
stringData:
    tailscale_client_id: ENC[AES256_GCM,data:FH89XTKmapTwEOeCgvKxMkw=,iv:7XVY1k10QWcZDLGe79EXgdWkrNH+XcXe+POmoIeKNM8=,tag:sTdi54k83i9MnNLNC0uoFg==,type:str]
    tailscale_client_secret: ENC[AES256_GCM,data:Z6YIOpE/7yrKOf26msBsSSgi2/feaFi4oavcAfW39sLAPTxxgsOKNYHeEaokCMtMHCPymGukFXnQcLyzIs1rig==,iv:6wIm767iTwUOtKlvpAruGMYZnRUQ3ex183Sja+4z6P4=,tag:TPaMUWBDbSKjcLjbLCblYA==,type:str]
sops:
    age:
        - recipient: age1smk9dv625g7ep25rs6qjft6gm3298gq0j56u82u0am0cxek5vazqq3z60w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aTU5dDVDaHVWNHJIcHc5
            bkhIOE8wWGs4OE12T2RxSEVidWpQTU9vampBCmNKandPdlNkN1pUOEZhMUlaSGVE
            NFpQVXRZcDhEb01ERDBzVDFaSzJRRnMKLS0tIFJlVGJzbkkvWVZmU1dnTmp3RTc1
            TGo5Mjk2SHdkb0dlRXc2SG4xZHZacFEK7XJgY1qLxzoFExLABuxa2Vu+d/ee3DTu
            oJKI5hJfp/vkVkrjYAbZGNNc7sC0LS0RFRKQuZNsqbyjI1qrIZeTXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T18:15:03Z"
    mac: ENC[AES256_GCM,data:PpQpNvSpxQJHkjg6pGgcK1iiOJSAENQnRhB71/vI+ojvHscKl+XrQ53QSXYQWIZgvzu2ah9XFvCTb2R9iSXOmifxgEY8Es7QdI3xV8y/rJ1+IoEls3JzWO9Ni0K94NawXlOgRZ6go9nge2avkXuflvIqxWMaMRjtQoCliIR/jVY=,iv:tnZXJDlpd/ftfiun8cddPKJPZXIC6RfkdV/7k1AG2Lo=,tag:2/kp2e1iDTAUSRWZnYTncA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
