apiVersion: v1
kind: Secret
metadata:
    name: sops
    namespace: flux-system
type: Opaque
stringData:
    tailscale_client_id: ENC[AES256_GCM,data:FH89XTKmapTwEOeCgvKxMkw=,iv:7XVY1k10QWcZDLGe79EXgdWkrNH+XcXe+POmoIeKNM8=,tag:sTdi54k83i9MnNLNC0uoFg==,type:str]
    tailscale_client_secret: ENC[AES256_GCM,data:Z6YIOpE/7yrKOf26msBsSSgi2/feaFi4oavcAfW39sLAPTxxgsOKNYHeEaokCMtMHCPymGukFXnQcLyzIs1rig==,iv:6wIm767iTwUOtKlvpAruGMYZnRUQ3ex183Sja+4z6P4=,tag:TPaMUWBDbSKjcLjbLCblYA==,type:str]
    postgres_user: ENC[AES256_GCM,data:4dBoDPU=,iv:n2Sm+T5Ei8XbuviGpFyl267sSkySGoD0CQJma06Rpsk=,tag:rpu6eC1Znlm0sSZ82hQQTw==,type:str]
    postgres_password: ENC[AES256_GCM,data:GWWr9dNHLh7QkGQAsic=,iv:YTOAhyBos6iMD8RAVv2k+UiimQ9/RxKQrpqLFj1WkDM=,tag:SUU0pnuiPs1liHyVKI11nQ==,type:str]
sops:
    age:
        - recipient: age1smk9dv625g7ep25rs6qjft6gm3298gq0j56u82u0am0cxek5vazqq3z60w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aTU5dDVDaHVWNHJIcHc5
            bkhIOE8wWGs4OE12T2RxSEVidWpQTU9vampBCmNKandPdlNkN1pUOEZhMUlaSGVE
            NFpQVXRZcDhEb01ERDBzVDFaSzJRRnMKLS0tIFJlVGJzbkkvWVZmU1dnTmp3RTc1
            TGo5Mjk2SHdkb0dlRXc2SG4xZHZacFEK7XJgY1qLxzoFExLABuxa2Vu+d/ee3DTu
            oJKI5hJfp/vkVkrjYAbZGNNc7sC0LS0RFRKQuZNsqbyjI1qrIZeTXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T14:58:15Z"
    mac: ENC[AES256_GCM,data:Z+ZQYwlG9CDlmkI3K6D4vOVOyI1i0n9Z7T4Zutp8VEBY8XTvx2h8QAwNopryuFXtIzmi0TWbTUXW2RgAd34v3YKq+9PmTEz+DB61ZERmXhEOa6fnuWTJ6YPMQthf5+3TdrZc7Ob5caqSUlkV/R4UVfCojlvHrV78oEIjy4QT2Cc=,iv:S17hQqzfjzsN1a8T1TrUx5VPZXDYyCqeKReH0urt8Xk=,tag:9CEMaJBAho2GOt8eetl+Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
