apiVersion: v1
kind: Secret
metadata:
    name: sops
    namespace: flux-system
type: Opaque
stringData:
    bitwarden_token: ENC[AES256_GCM,data:wYvklnQYPCZPYzE7g2IhZbDG3EHlmUpkfgyE0XfUkfmE6LFWgCuNlGli7i3YZ4sXwHboZq/cEZ3CxSJZAJQqykPRuswn2BLTub2eMKESk/9nB3GEZwj8Mdfn8GLbDA==,iv:iso6CnRVqWbrT6XgvDU54ug4ZpsfiLBxiCxRP8o9UCI=,tag:V5gsB1Uv51NcvDOcFtBT3g==,type:str]
    tailscale_client_id: ENC[AES256_GCM,data:FH89XTKmapTwEOeCgvKxMkw=,iv:7XVY1k10QWcZDLGe79EXgdWkrNH+XcXe+POmoIeKNM8=,tag:sTdi54k83i9MnNLNC0uoFg==,type:str]
    tailscale_client_secret: ENC[AES256_GCM,data:Z6YIOpE/7yrKOf26msBsSSgi2/feaFi4oavcAfW39sLAPTxxgsOKNYHeEaokCMtMHCPymGukFXnQcLyzIs1rig==,iv:6wIm767iTwUOtKlvpAruGMYZnRUQ3ex183Sja+4z6P4=,tag:TPaMUWBDbSKjcLjbLCblYA==,type:str]
    postgres_user: ENC[AES256_GCM,data:4dBoDPU=,iv:n2Sm+T5Ei8XbuviGpFyl267sSkySGoD0CQJma06Rpsk=,tag:rpu6eC1Znlm0sSZ82hQQTw==,type:str]
    postgres_password: ENC[AES256_GCM,data:GWWr9dNHLh7QkGQAsic=,iv:YTOAhyBos6iMD8RAVv2k+UiimQ9/RxKQrpqLFj1WkDM=,tag:SUU0pnuiPs1liHyVKI11nQ==,type:str]
    acme_email: ENC[AES256_GCM,data:eHxrd8Ya2SSPDPXMKfBAa/3xbd2l58w=,iv:4XA8zN/2vX2uFT1sSm7WH8F0rPQ5HM3tHi9NzEfczck=,tag:TOU9qF8FGNPIKErmiQ2WZA==,type:str]
sops:
    age:
        - recipient: age1smk9dv625g7ep25rs6qjft6gm3298gq0j56u82u0am0cxek5vazqq3z60w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aTU5dDVDaHVWNHJIcHc5
            bkhIOE8wWGs4OE12T2RxSEVidWpQTU9vampBCmNKandPdlNkN1pUOEZhMUlaSGVE
            NFpQVXRZcDhEb01ERDBzVDFaSzJRRnMKLS0tIFJlVGJzbkkvWVZmU1dnTmp3RTc1
            TGo5Mjk2SHdkb0dlRXc2SG4xZHZacFEK7XJgY1qLxzoFExLABuxa2Vu+d/ee3DTu
            oJKI5hJfp/vkVkrjYAbZGNNc7sC0LS0RFRKQuZNsqbyjI1qrIZeTXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T05:08:44Z"
    mac: ENC[AES256_GCM,data:n16LE+vglMfujp8mnubsqje/i3hVlbi99fATuzF8kdkiA2Dy5KmWq2aWuG/QKOFrsdk6YeOrGsTXellkd02HEhAAq4Lf06GbTxgBzmyM/XrtRrDDqk6n9M3dEAXuuF3ko9WgbXr1wBXAY1t4bjPVQyhGppywBO4k0YXShKCT1kU=,iv:Wz4dCmT07ygUoM0gEv5UhZl9flRJJaBqd5XM1PShlFo=,tag:wpgghM6UNlo8Qjg1S8c42A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
