apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel-device-plugins
  namespace: kube-system
spec:
  interval: 1h
  url: https://intel.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 1h
  url: oci://registry.k8s.io/nfd/charts/node-feature-discovery
  ref:
    tag: 0.18.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m0s
  install:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: kube-system
spec:
  dependsOn:
    - name: node-feature-discovery
  interval: 5m0s
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: intel-device-plugins-operator
      sourceRef:
        kind: HelmRepository
        name: intel-device-plugins
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-gpu
  namespace: kube-system
spec:
  dependsOn:
    - name: intel-device-plugins-operator
    - name: node-feature-discovery
  interval: 5m0s
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: intel-device-plugins-gpu
      sourceRef:
        kind: HelmRepository
        name: intel-device-plugins
  values:
    nodeFeatureRule: true
