services:
  mimir:
    image: grafana/mimir:3.0.3
    container_name: mimir
    command: ["-config.file=/etc/mimir.yaml"]
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - type: volume
        source: nfs-general-data
        target: /etc/mimir.yaml
        volume:
          subpath: observability/mimir/mimir.yaml
      - type: volume
        source: nfs-general-data
        target: /data
        volume:
          subpath: observability/mimir/data

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway" # Need this in order to use `host.docker.internal` domain
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - type: volume
        source: nfs-general-data
        target: /etc/grafana/provisioning/datasources
        volume:
          subpath: observability/grafana

volumes:
  nfs-general-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.1.11,rw,nolock,soft,nfsvers=4"
      device: ":/mnt/general/data"
