apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  labels:
    app: jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-config-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/jellyfin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  labels:
    app: jellyfin
spec:
  capacity:
    storage: 2Ti
  accessModes: [ReadOnlyMany]
  storageClassName: nfs-csi-media
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-media-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/media
