apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: groundhog2k
  namespace: dns
spec:
  interval: 1h
  url: https://groundhog2k.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etcd
  namespace: dns
spec:
  interval: 5m0s
  chart:
    spec:
      chart: etcd
      version: "1.*"
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
  install:
    remediation:
      retries: 3
  values:
    replicas: 1
    storage:
      requestedSize: 1Gi
