apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app: prometheus
spec:
  capacity:
    storage: 60Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: prometheus-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/observability/prometheus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: grafana-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/observability/grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  labels:
    app: loki
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: loki-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/observability/loki
