apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth-credentials
  namespace: tailscale
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale_client_id
    - secretKey: client_secret
      remoteRef:
        key: tailscale_client_secret
