apiVersion: v1
kind: PersistentVolume
metadata:
  name: adventurelog-media-pv
  labels:
    app: adventurelog
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: adventurelog-media-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/adventurelog/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adventurelog-db-pv
  labels:
    app: adventurelog
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: adventurelog-db-pv
    volumeAttributes:
      server: 192.168.1.11
      share: /mnt/general/data/adventurelog/db
