apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventurelog-media-pvc
  namespace: adventurelog
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Gi
  volumeName: adventurelog-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventurelog-db-pvc
  namespace: adventurelog
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
  volumeName: adventurelog-db-pv
