apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adventurelog-secret
  namespace: adventurelog
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: postgres-password
      remoteRef:
        key: adventurelog_postgres_password
    - secretKey: django-secret-key
      remoteRef:
        key: adventurelog_django_secret_key
