apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  namespace: flux-system
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: address
      remoteRef:
        key: discord_webhook_url
